cc_library(
    name = "square_calculator",
    srcs = ["square_calculator.cc"],
    deps = [
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework/port:status",
    ],
    visibility = [
        "//visibility:public",
    ],
)

